// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package appdb

import (
	"database/sql"
	"time"
)

type Script struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Content     string    `json:"content"`
	AccessLevel string    `json:"access_level"`
	Created     time.Time `json:"created"`
	Updated     time.Time `json:"updated"`
}

type Secret struct {
	ID      int64     `json:"id"`
	Key     string    `json:"key"`
	Value   []byte    `json:"value"`
	Created time.Time `json:"created"`
	Updated time.Time `json:"updated"`
}

type User struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	Role      string       `json:"role"`
	Created   time.Time    `json:"created"`
	Updated   time.Time    `json:"updated"`
	Lastlogin sql.NullTime `json:"lastlogin"`
}

type Var struct {
	ID      int64     `json:"id"`
	Key     string    `json:"key"`
	Value   string    `json:"value"`
	Created time.Time `json:"created"`
	Updated time.Time `json:"updated"`
}
