// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package appdb

import (
	"context"
)

type Querier interface {
	CreateScript(ctx context.Context, arg CreateScriptParams) (Script, error)
	CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVar(ctx context.Context, arg CreateVarParams) (Var, error)
	DeleteScript(ctx context.Context, name string) error
	DeleteSecret(ctx context.Context, key string) error
	DeleteUser(ctx context.Context, email string) error
	DeleteVar(ctx context.Context, key string) error
	GetScript(ctx context.Context, name string) (Script, error)
	GetSecret(ctx context.Context, key string) (Secret, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVar(ctx context.Context, key string) (Var, error)
	ListScripts(ctx context.Context) ([]Script, error)
	ListScriptsByAccess(ctx context.Context, accessLevel string) ([]Script, error)
	ListSecrets(ctx context.Context) ([]Secret, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListVars(ctx context.Context) ([]Var, error)
	UpdateScript(ctx context.Context, arg UpdateScriptParams) (Script, error)
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error)
	UpdateUserLastLogin(ctx context.Context, id int64) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateVar(ctx context.Context, arg UpdateVarParams) (Var, error)
}

var _ Querier = (*Queries)(nil)
